### ISSUE TITLE
Add support for partial clones

### ISSUE THREAD

**Issue by sliekens** [dotnet/sourcelink#1111]
Hello,

I would like to use treeless clones or blobless clones in my GitHub Actions workflow, but Source Link does not support it.

More info https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

My workflow

``` yml
steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0 # (no history limit)
      filter: tree:0

  - name: Build
    run: dotnet build
```

My build fails due to Source Link not supporting this configuration.

> /github/home/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(25,5): error : Error reading git repository information: Unsupported repository version 1. Only versions up to 0 are supported. [/__w/gw2sdk/gw2sdk/GW2SDK/GW2SDK.csproj::TargetFramework=netstandard2.0]
> /github/home/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(25,5): warning : Unable to locate repository with working directory that contains directory '/__w/gw2sdk/gw2sdk/GW2SDK'. [/__w/gw2sdk/gw2sdk/GW2SDK/GW2SDK.csproj::TargetFramework=netstandard2.0]
