### ISSUE TITLE
Sourcelink not working if snupkg is present, but works if it is not there

### ISSUE THREAD

**Issue by taori** [dotnet/sourcelink#745]
Okay - So i have tried to set up my project with SourceLink and noticed that some versions did support stepping in while others did not.

I ended up noticing that the versions which DID work for me were those where CI failed to upload snupkg files because of empty symbols so i compared a couple commits and noticed that one configuration that did work for me was the following:

- Create compilation WITH snupkg generation
- DELETE snupkg
- Upload nupkg

A library where the snupkg file was missing worked successfully, but if the same configuration also uploaded its snupkg, source link did not allow me to step into code anymore.

My setup is this:

SourceLink.props
```
<Project>
	<PropertyGroup>
		<!-- https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/ -->

		<!-- Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>

		<!-- Embed source files that are not tracked by the source control manager in the PDB -->
		<EmbedUntrackedSources>true</EmbedUntrackedSources>

		<!-- Recommended: Embed symbols containing Source Link in the main file (exe/dll) -->
		<DebugType>embedded</DebugType>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<DebugSymbols>true</DebugSymbols>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>
</Project>
```

Directory.Build.props
```
<Project>
	<PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<SourceRoot Include="$(MSBuildThisFileDirectory)/"/>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
	</ItemGroup>

	<Import Project="..\build\SourceLink.props"/>
</Project>
```

``` ProjectFIle
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix>beta</VersionSuffix>
		<IsPackable>true</IsPackable>

		<Copyright>Copyright © AUTHOR CURRENTYEAR</Copyright>
		<Description>MyPackageId</Description>
		<PackageId>MyPackageId</PackageId>
		<Authors>AUTHOR</Authors>
		<Product>MyProductName</Product>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>

		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/GITOWNER/GITPROJECT.git</RepositoryUrl>
		<PackageProjectUrl>https://github.com/GITOWNER/GITPROJECT</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	</PropertyGroup>
</Project>
```

workflow.yml
```
    - name: Restore dependencies
      run: dotnet restore src/All.sln
    - name: Build
      run: dotnet build src/All.sln --verbosity $verbosity -c $configuration --no-restore 
    - name: Test
      run: dotnet test src/All.sln --verbosity $verbosity -c $configuration --no-build 
              
    - name: Pack
      if: ${{ needs.environment.outputs.publishRelease == 'True' }}
      run: dotnet pack src/MyLibrary/MyLibrary.csproj --verbosity $verbosity -c $configuration -o artifacts/nupkg --no-build /p:VersionSuffix=$versionSuffix

    - name: Remove snupkg
      if: ${{ needs.environment.outputs.publishRelease == 'True' }}
      run: find artifacts/nupkg/ -name "*.snupkg" -type f -delete
      
    - name: Release
      if: ${{ needs.environment.outputs.publishRelease == 'True' }}
      run: dotnet nuget push "artifacts/nupkg/*.nupkg" -k $NUGETKEY -s https://api.nuget.org/v3/index.json
      env:
        NUGETKEY: ${{ secrets.NUGET }}
```

I tried other property / build script permutations, but with embedded+deleted snupkg was a combination that worked
